FROM nginx
COPY index.html /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY js/ /usr/share/nginx/html/js
COPY sign_up/ /usr/share/nginx/html/sign_up
COPY log_in/ /usr/share/nginx/html/log_in
ADD default.conf /etc/nginx/conf.d/default.conf
