FROM nginx
COPY index.html /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY sign_up/ /usr/share/nginx/html/sign_up
COPY log_in/ /usr/share/nginx/html/log_in
COPY log_out/ /usr/share/nginx/html/log_out
COPY choose_skill/ /usr/share/nginx/html/choose_skill
COPY set_up_habit/ /usr/share/nginx/html/set_up_habit
COPY record/ /usr/share/nginx/html/record
COPY calendar/ /usr/share/nginx/html/calendar
COPY charts/ /usr/share/nginx/html/charts
COPY coaching/ /usr/share/nginx/html/coaching
COPY edit_habit/ /usr/share/nginx/html/edit_habit
COPY edit_skill/ /usr/share/nginx/html/edit_skill
COPY gamifying/ /usr/share/nginx/html/gamifying
COPY header/ /usr/share/nginx/html/header
ADD default.conf /etc/nginx/conf.d/default.conf
