FROM nginx
COPY index.html /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY js/ /usr/share/nginx/html/js
COPY sign_up/ /usr/share/nginx/html/sign_up
COPY log_in/ /usr/share/nginx/html/log_in
COPY choose_skill/ /usr/share/nginx/html/choose_skill
COPY set_up_habit/ /usr/share/nginx/html/set_up_habit
COPY record/ /usr/share/nginx/html/record
COPY calendar/ /usr/share/nginx/html/calendar
COPY charts/ /usr/share/nginx/html/charts
ADD default.conf /etc/nginx/conf.d/default.conf
